model all non-compound entries in the schema (#57)
This PR adds a new pydantic model class
`EcosystemStudyFeaturesWithoutCompounds` holding all non-compound
fields. It also renames the default model class from
`EcosystemStudyFeatures` to `EcosystemStudyFeaturesSimple` and slightly
adjusts it.

This also tries to align the field descriptions with the column "Frage"
of the [Fragenkatalog google
table](https://docs.google.com/spreadsheets/d/1MyEZTLOm85ZNxuTSHxwJLxaAXiCGLt-mMozUkBlGzJE/edit?gid=0#gid=0).

Implements #62.

Requires:
- #47, especially list of
[non-compounds](https://github.com/DFKI-NLP/kibad-llm/issues/47#issuecomment-3469046360)
- [db summary on updated
data](https://github.com/DFKI-NLP/kibad-llm/pull/53#issuecomment-3468264530)
(with script from #20)
 - #64
 - #65
 - #67

Details:
- rename pydantic model to `EcosystemStudyFeaturesSimple` and adjust
fields to contain only:
   - `habitat`, `natural_region`, `climate` (added), `landuse` (added)
- i.e., remove `location_federal_state` since it is an compound entry
(but keep its enum `LocationFederalStateEnum` for later use)
- create `EcosystemStudyFeaturesWithoutCompounds` with all non-compound
entries: add fields (based on [Fragenkatalog google
table](https://docs.google.com/spreadsheets/d/1MyEZTLOm85ZNxuTSHxwJLxaAXiCGLt-mMozUkBlGzJE/edit?gid=0#gid=0)
for singl vs multi label and [db summary on updated
data](https://github.com/DFKI-NLP/kibad-llm/pull/53#issuecomment-3468264530)
for value sets and types):
   - `habitat` multi-label. closed value set (6).
   - `natural_region` multi-label. closed value set (6).
   - `climate` multi-label. closed value set (9).
   - `landuse` multi-label. closed value set (16).
   - `spatial_extent` single-label, optional. closed value set (8).
   - `spatial_resolution` single-label, optional. closed value set (8).
   - `spatial_measurements` single-label, optional. numeric (218).
- `temporal_extent` single-label, optional. numeric or closed value set
(113). TODO: FIX "Art der Information" IN [Fragenkatalog google
table](https://docs.google.com/spreadsheets/d/1MyEZTLOm85ZNxuTSHxwJLxaAXiCGLt-mMozUkBlGzJE/edit?gid=0#gid=0):
should not be closed value ("Feste Kategorien")!
   - `temporal_resolution` single-label, optional. closed value set (8).
- `temporal_measurements` single-label, optional. numeric (79). INCLUDES
ONE NEGATIVE ENTRY (`-3`)!
- `start_year` single-label, optional. numeric (115). INCLUDES ONE VERY
LOW VALUE (`948`)
- `end_year` single-label, optional. numeric (72). INCLUDES TWO VERY LOW
VALUES (`200`, `209`) AND ONE VERY LARGE VALUE (`20018`)
   - `method` multi-label. closed value set (8).
   - `study_type` multi-label. closed value set (8).
   - `project` single-label, optional. open value set (110).
   - `biodiversity_level` multi-label. closed value set (7).
   - `biodiversity_variable` multi-label. open value set (156).
- `transformation_potential` single-label, optional. closed value set
(4).
- add the following enums (#entries, IMPORTANT: numbers of entries per
field above may contain `NaN`s, so the numbers here may be different
since they only contain actual values):
    - `EcosystemTypeTermEnum` (32)
    - `ClimateEnum` (9)
    - `LanduseEnum` (16)
    - `SpatialExtentEnum` (7)
    - `SpatialResolutionEnum` (7).
    - `TemporalResolutionEnum` (7)
    - `MethodEnum` (8)
    - `StudyTypeEnum` (8)
    - `BiodiversityLevelEnum` (7)
    - `TransformationPotentialEnum` (3)
- minor fixes in `_template` (without schema): mention "Semikolon" as
separator, add task constraints
- adjust `evaluate` config: add new fields to the preprocessing mapping
of the predictions
- add `evaluate` config to be skipped from `codespell` checks since the
mapping now contains German words
 - adjust templates, tests and fixture data
- remove `test_predict_without_schema_fast_dev_run()` since this is
already covered by extractor tests

Notes:
- see comments in CAPITAL letters above for potential todos regarding
the data (!)
 - also see #59
 - I successfully ran all tests (including the slow ones) locally.

TODO:
- [x] **handle all TODOs in the new code** (@leonhardhennig please
provide feedback)
 - [x] execute all slows tests
- but result is not 100% stable, I just re-run it when such an error
occurred: `FAILED
tests/integration/test_predict.py::test_prediction[25ABQZIH.pdf] -
TypeError: 'NoneType' object is not iterable`. This error means the llm
call failed at all (json decoding / validation error, can not connect to
the llm, or the llm backend failed because of e.g. too long input text)